### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by xys20071111** [AIGODLIKE/M4A1TOOLS#2]
Blender版本：4.1.1  
插件版本：2.0.2  
操作系统：Debian GNU/Linux  
下载来源：GitHub Release
错误日志：
```
Traceback (most recent call last):
  File "/home/xys/.local/share/Steam/steamapps/common/Blender/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xys/.local/share/Steam/steamapps/common/Blender/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'M4A1TOOLS-2'
```

**Comment by iloveyehan** [comment]
更改插件文件夹'M4A1TOOLS-2' 为'M4A1TOOLS'

**Comment by xys20071111** [comment]
> 更改插件文件夹'M4A1TOOLS-2' 为'M4A1TOOLS'

根据您给的方法，在blender的插件文件夹里找到了`M4A1TOOLS-2.02`
将其重命名为`M4A1TOOLS-2`后问题解决了
